In [1]:
# Chi square :  Cat vs Cat
# t-test : Cat vs num. Two categories. Varibales <= 30.
# z-test : Cat vs num. Two Categories. Variables>30.
# Anova : Cat vs num. >= 3 Categories

In [2]:
# Out Standing Principle(OSP) : Loan amount to left to repay.
# Portfolio At Risk : OSP when DPD>0.
# GNPA : NPA 
# Net NPA : GNPA - Provisioning
# SMA1,SMA2,SMA3

In [3]:
# Importing basic libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
import warnings
warnings.filterwarnings('ignore')

#### Changing the current working directory

In [4]:
os.chdir('C:\LEARNBAY CLASSES\learnbay projects\FINANCE NEW DOMAIN')

In [5]:
os.getcwd()

'C:\\LEARNBAY CLASSES\\learnbay projects\\FINANCE NEW DOMAIN'

In [6]:
df1=pd.read_excel('dataset1.xlsx')
df2=pd.read_excel('dataset2.xlsx')

#### Shape of both datasets

In [7]:
print(f'Dataset1 has {df1.shape[0]} rows and {df1.shape[1]} columns.')
print(f'Dataset2 has {df2.shape[0]} rows and {df2.shape[1]} columns.')

Dataset1 has 51336 rows and 26 columns.
Dataset2 has 51336 rows and 62 columns.


#### Peeking into both datasets

In [8]:
df1.head()

PROSPECTID  Total_TL  Tot_Closed_TL  Tot_Active_TL  Total_TL_opened_L6M  \
0           1         5              4              1                    0   
1           2         1              0              1                    0   
2           3         8              0              8                    1   
3           4         1              0              1                    1   
4           5         3              2              1                    0   

   Tot_TL_closed_L6M  pct_tl_open_L6M  pct_tl_closed_L6M  pct_active_tl  \
0                  0            0.000                0.0          0.200   
1                  0            0.000                0.0          1.000   
2                  0            0.125                0.0          1.000   
3                  0            1.000                0.0          1.000   
4                  0            0.000                0.0          0.333   

   pct_closed_tl  ...  CC_TL  Consumer_TL  Gold_TL  Home_TL  PL_TL  \
0          0.800  ...      0            0        1        0      4   
1          0.000  ...      0            1        0        0      0   
2          0.000  ...      0            6        1        0      0   
3          0.000  ...      0            0        0        0      0   
4          0.667  ...      0            0        0        0      0   

   Secured_TL  Unsecured_TL  Other_TL  Age_Oldest_TL  Age_Newest_TL  
0           1             4         0             72             18  
1           0             1         0              7              7  
2           2             6         0             47              2  
3           0             1         1              5              5  
4           3             0         2            131             32  

[5 rows x 26 columns]

In [9]:
df2.head()

PROSPECTID  time_since_recent_payment  time_since_first_deliquency  \
0           1                        549                           35   
1           2                         47                       -99999   
2           3                        302                           11   
3           4                     -99999                       -99999   
4           5                        583                       -99999   

   time_since_recent_deliquency  num_times_delinquent  max_delinquency_level  \
0                            15                    11                     29   
1                        -99999                     0                 -99999   
2                             3                     9                     25   
3                        -99999                     0                 -99999   
4                        -99999                     0                 -99999   

   max_recent_level_of_deliq  num_deliq_6mts  num_deliq_12mts  \
0                         29               0                0   
1                          0               0                0   
2                         25               1                9   
3                          0               0                0   
4                          0               0                0   

   num_deliq_6_12mts  ...  pct_CC_enq_L6m_of_L12m  pct_PL_enq_L6m_of_ever  \
0                  0  ...                     0.0                     0.0   
1                  0  ...                     0.0                     0.0   
2                  8  ...                     0.0                     0.0   
3                  0  ...                     0.0                     0.0   
4                  0  ...                     0.0                     0.0   

   pct_CC_enq_L6m_of_ever  max_unsec_exposure_inPct  HL_Flag  GL_Flag  \
0                     0.0                    13.333        1        0   
1                     0.0                     0.860        0        0   
2                     0.0                  5741.667        1        0   
3                     0.0                     9.900        0        0   
4                     0.0                -99999.000        0        0   

   last_prod_enq2  first_prod_enq2  Credit_Score  Approved_Flag  
0              PL               PL           696             P2  
1    ConsumerLoan     ConsumerLoan           685             P2  
2    ConsumerLoan           others           693             P2  
3          others           others           673             P2  
4              AL               AL           753             P1  

[5 rows x 62 columns]

#### We observe that some values in both the datasets are -99999. These values indicate missing values.

#### Analyzing the data types of both datasets

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   PROSPECTID            51336 non-null  int64  
 1   Total_TL              51336 non-null  int64  
 2   Tot_Closed_TL         51336 non-null  int64  
 3   Tot_Active_TL         51336 non-null  int64  
 4   Total_TL_opened_L6M   51336 non-null  int64  
 5   Tot_TL_closed_L6M     51336 non-null  int64  
 6   pct_tl_open_L6M       51336 non-null  float64
 7   pct_tl_closed_L6M     51336 non-null  float64
 8   pct_active_tl         51336 non-null  float64
 9   pct_closed_tl         51336 non-null  float64
 10  Total_TL_opened_L12M  51336 non-null  int64  
 11  Tot_TL_closed_L12M    51336 non-null  int64  
 12  pct_tl_open_L12M      51336 non-null  float64
 13  pct_tl_closed_L12M    51336 non-null  float64
 14  Tot_Missed_Pmnt       51336 non-null  int64  
 15  Auto_TL            

In [11]:
#### We observe that in dataset1 there is no object datatype. So there is no need to change datatype in this set.

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 62 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   PROSPECTID                    51336 non-null  int64  
 1   time_since_recent_payment     51336 non-null  int64  
 2   time_since_first_deliquency   51336 non-null  int64  
 3   time_since_recent_deliquency  51336 non-null  int64  
 4   num_times_delinquent          51336 non-null  int64  
 5   max_delinquency_level         51336 non-null  int64  
 6   max_recent_level_of_deliq     51336 non-null  int64  
 7   num_deliq_6mts                51336 non-null  int64  
 8   num_deliq_12mts               51336 non-null  int64  
 9   num_deliq_6_12mts             51336 non-null  int64  
 10  max_deliq_6mts                51336 non-null  int64  
 11  max_deliq_12mts               51336 non-null  int64  
 12  num_times_30p_dpd             51336 non-null  int64  
 13  n

#### Now merging the two datasets based on common column. For this, we first find the common column.

In [13]:
for i in df1.columns:
    for j in df2.columns:
        if i==j:
            print('Common Column is : ',i)

Common Column is :  PROSPECTID


In [14]:
df = pd.merge(df1,df2,how='inner',left_on='PROSPECTID',right_on='PROSPECTID')

In [15]:
df.shape

(51336, 87)

#### Converting missing values(-99999) in the dataset  to null values

In [16]:
df[df==-99999]=np.nan

#### Finding null values in each column

In [17]:
for i in df.columns:
    print(i,'-----',df[i].isnull().sum())

PROSPECTID ----- 0
Total_TL ----- 0
Tot_Closed_TL ----- 0
Tot_Active_TL ----- 0
Total_TL_opened_L6M ----- 0
Tot_TL_closed_L6M ----- 0
pct_tl_open_L6M ----- 0
pct_tl_closed_L6M ----- 0
pct_active_tl ----- 0
pct_closed_tl ----- 0
Total_TL_opened_L12M ----- 0
Tot_TL_closed_L12M ----- 0
pct_tl_open_L12M ----- 0
pct_tl_closed_L12M ----- 0
Tot_Missed_Pmnt ----- 0
Auto_TL ----- 0
CC_TL ----- 0
Consumer_TL ----- 0
Gold_TL ----- 0
Home_TL ----- 0
PL_TL ----- 0
Secured_TL ----- 0
Unsecured_TL ----- 0
Other_TL ----- 0
Age_Oldest_TL ----- 40
Age_Newest_TL ----- 40
time_since_recent_payment ----- 4291
time_since_first_deliquency ----- 35949
time_since_recent_deliquency ----- 35949
num_times_delinquent ----- 0
max_delinquency_level ----- 35949
max_recent_level_of_deliq ----- 0
num_deliq_6mts ----- 0
num_deliq_12mts ----- 0
num_deliq_6_12mts ----- 0
max_deliq_6mts ----- 12890
max_deliq_12mts ----- 10832
num_times_30p_dpd ----- 0
num_times_60p_dpd ----- 0
num_std ----- 0
num_std_6mts ----- 0
num_std_1

#### Removing columns if null values are greater than 25% or less than 1%.

In [18]:
cols_to_be_removed=[]
for i in df.columns:
    if df[i].isnull().sum()>0:
        if df[i].isnull().sum()>0.25*df.shape[0] or df[i].isnull().sum()<.01*df.shape[0]:
            cols_to_be_removed.append(i)
print('Columns to be removed are : ')
print(cols_to_be_removed)

Columns to be removed are : 
['Age_Oldest_TL', 'Age_Newest_TL', 'time_since_first_deliquency', 'time_since_recent_deliquency', 'max_delinquency_level', 'max_deliq_6mts', 'pct_currentBal_all_TL', 'CC_utilization', 'PL_utilization', 'max_unsec_exposure_inPct']


#### Our final dataset is:

In [19]:
df=df.drop(columns=cols_to_be_removed)
df.shape

(51336, 77)

#### Splitting the data into Dependent(y) and Independent Columns(x)

In [20]:
x=df.drop(columns=['Approved_Flag'])
y=df['Approved_Flag']

In [21]:
df.head()

PROSPECTID  Total_TL  Tot_Closed_TL  Tot_Active_TL  Total_TL_opened_L6M  \
0           1         5              4              1                    0   
1           2         1              0              1                    0   
2           3         8              0              8                    1   
3           4         1              0              1                    1   
4           5         3              2              1                    0   

   Tot_TL_closed_L6M  pct_tl_open_L6M  pct_tl_closed_L6M  pct_active_tl  \
0                  0            0.000                0.0          0.200   
1                  0            0.000                0.0          1.000   
2                  0            0.125                0.0          1.000   
3                  0            1.000                0.0          1.000   
4                  0            0.000                0.0          0.333   

   pct_closed_tl  ...  pct_PL_enq_L6m_of_L12m  pct_CC_enq_L6m_of_L12m  \
0          0.800  ...                     0.0                     0.0   
1          0.000  ...                     0.0                     0.0   
2          0.000  ...                     0.0                     0.0   
3          0.000  ...                     0.0                     0.0   
4          0.667  ...                     0.0                     0.0   

   pct_PL_enq_L6m_of_ever  pct_CC_enq_L6m_of_ever  HL_Flag  GL_Flag  \
0                     0.0                     0.0        1        0   
1                     0.0                     0.0        0        0   
2                     0.0                     0.0        1        0   
3                     0.0                     0.0        0        0   
4                     0.0                     0.0        0        0   

   last_prod_enq2  first_prod_enq2  Credit_Score  Approved_Flag  
0              PL               PL           696             P2  
1    ConsumerLoan     ConsumerLoan           685             P2  
2    ConsumerLoan           others           693             P2  
3          others           others           673             P2  
4              AL               AL           753             P1  

[5 rows x 77 columns]

#### Splitting the data into train and test

In [22]:
numerical_columns=[]
categorical_columns=[]
for i in df.columns:
    if df[i].dtypes=='object':
        categorical_columns.append(i)
    else:
        numerical_columns.append(i)
    

In [23]:
print('Categorical Columns are :')
pd.DataFrame(categorical_columns)

Categorical Columns are :


0
0    MARITALSTATUS
1        EDUCATION
2           GENDER
3   last_prod_enq2
4  first_prod_enq2
5    Approved_Flag

In [24]:
print('Numerical Columns are :')
pd.DataFrame(numerical_columns)

Numerical Columns are :


0
0               PROSPECTID
1                 Total_TL
2            Tot_Closed_TL
3            Tot_Active_TL
4      Total_TL_opened_L6M
..                     ...
66  pct_PL_enq_L6m_of_ever
67  pct_CC_enq_L6m_of_ever
68                 HL_Flag
69                 GL_Flag
70            Credit_Score

[71 rows x 1 columns]

In [25]:
print(f'We have {len(numerical_columns)} Numerical columns and {len(categorical_columns)} Categorical columns.')

We have 71 Numerical columns and 6 Categorical columns.


#### Imputing missing values using KNN imputer.

In [26]:
#### Imputing null values
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=5)
df_imputed=pd.DataFrame(imputer.fit_transform(df[numerical_columns]),columns=numerical_columns)

#### concatenating numerical and categorical columns.

In [27]:
final_df_imputed=pd.concat((df_imputed,df[categorical_columns]),axis=1)

#### Chi Square test : For analysing important categorical columns.

In [28]:
from scipy.stats import chi2_contingency

In [29]:
for i in categorical_columns:
    chi2,p_value,_,_=chi2_contingency(pd.crosstab(final_df_imputed[i],final_df_imputed['Approved_Flag']))
    print(i,'------',p_value)

MARITALSTATUS ------ 2.7588304433709322e-257
EDUCATION ------ 8.464676085080213e-38
GENDER ------ 0.0002450667989541709
last_prod_enq2 ------ 0.0
first_prod_enq2 ------ 0.0
Approved_Flag ------ 0.0


#### For every categorical column, pvalue is less than 0.05. So we reject null hypothesis. Our null hypothesis was that there is no relationship between the categorical columns. So all categorical variables are significant variables.

#### Analysing Multi Collinearity using Variance Inflation factor

In [30]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

#### Removing PROSPECTID column because its a Personal Identifier.

In [31]:
numerical_columns.remove ('PROSPECTID')

In [32]:
vif_data=final_df_imputed[numerical_columns]
total_columns=vif_data.shape[1]
columns_to_be_kept=[]
column_index=0

In [33]:
for i in range(0,total_columns):
    vif_value=variance_inflation_factor(vif_data,column_index)
    print(column_index,'------',vif_value)
    column_index+=1
    if vif_value<10:
        columns_to_be_kept.append(numerical_columns[i])
  

0 ------ inf
1 ------ inf
2 ------ inf
3 ------ 8.200392749399086
4 ------ 6.728917067986167
5 ------ 5.448123385446685
6 ------ 4.025651895201404
7 ------ inf
8 ------ 1154.9070399619238
9 ------ 15.027922432428458
10 ------ 8.925061333806436
11 ------ 3.7839174351476967
12 ------ 4.517664766598121
13 ------ 2.1367110714807045
14 ------ inf
15 ------ inf
16 ------ inf
17 ------ inf
18 ------ inf
19 ------ inf
20 ------ inf
21 ------ inf
22 ------ inf
23 ------ 1.5028686387631633
24 ------ 7.615797203831498
25 ------ 5.090107563326957
26 ------ inf
27 ------ inf
28 ------ inf
29 ------ 2.1186367091835754
30 ------ 13.667990931538197
31 ------ 8.243697374786564
32 ------ 6.117354219932596
33 ------ 14.045755463703415
34 ------ 21.810974212129192
35 ------ 1.5598652366821677
36 ------ 2.547274692120014
37 ------ 3.1031475514844202
38 ------ 2.1934716608130276
39 ------ 7.382593462764802
40 ------ 9.298471893381436
41 ------ 2.724345525129291
42 ------ 6.355263028774884
43 ------ 7.948924

In [34]:
len(columns_to_be_kept)

38

In [35]:
df_after_vif=final_df_imputed[columns_to_be_kept + categorical_columns]

In [36]:
df_after_vif.shape

(51336, 44)

#### ANOVA Test

In [37]:
from scipy.stats import f_oneway

In [38]:
columns_to_be_kept_numerical=[]
for i in columns_to_be_kept:
  a=list(df_after_vif[i])
  b=list(df_after_vif['Approved_Flag'])

  group_p1=[value for value,group in zip(a,b) if group=='P1']
  group_p2=[value for value,group in zip(a,b) if group=='P2']
  group_p3=[value for value,group in zip(a,b) if group=='P3']
  group_p4=[value for value,group in zip(a,b) if group=='P4']

  f_statistic,p_value=f_oneway(group_p1,group_p2,group_p3,group_p4)
  if p_value<0.05:
    columns_to_be_kept_numerical.append(i)

In [39]:
len(columns_to_be_kept_numerical)

34

In [40]:
df_after_anova=df_after_vif[columns_to_be_kept_numerical + categorical_columns]

In [41]:
df_after_anova.shape

(51336, 40)

In [42]:
#### Our final dataset has 40 variables.

#### Analyzing unique values in the categorical columns of our final dataset

In [43]:
for i in df_after_anova.columns[df_after_anova.dtypes==object]:
    print(i)
    print(df_after_anova[i].unique())
    print('*'*10)
    

MARITALSTATUS
['Married' 'Single']
**********
EDUCATION
['12TH' 'GRADUATE' 'SSC' 'POST-GRADUATE' 'UNDER GRADUATE' 'OTHERS'
 'PROFESSIONAL']
**********
GENDER
['M' 'F']
**********
last_prod_enq2
['PL' 'ConsumerLoan' 'others' 'AL' 'CC' 'HL']
**********
first_prod_enq2
['PL' 'ConsumerLoan' 'others' 'AL' 'HL' 'CC']
**********
Approved_Flag
['P2' 'P1' 'P3' 'P4']
**********


#### The data in all the columns except EDUCATION and Approved_Flag does not seem to follow any order. So we will use one hot encoding for these columns.

In [44]:
df_after_anova=df_after_anova.drop(columns=['EDUCATION','Approved_Flag'])
df_after_anova=pd.get_dummies(df_after_anova,drop_first=True,dtype=int)

#### Now concatenating the dropped columns 'EDUCATION','Approved_Flag' to the dataset df3 again.

In [45]:
df_after_anova=pd.concat([df_after_anova,df_after_vif['EDUCATION'],df_after_vif['Approved_Flag']],axis=1)

In [46]:
df_after_anova.shape

(51336, 48)

#### Now converting columns Education and Approved_Flag to numeric data type.

In [47]:
df_after_anova.EDUCATION.unique()

array(['12TH', 'GRADUATE', 'SSC', 'POST-GRADUATE', 'UNDER GRADUATE',
       'OTHERS', 'PROFESSIONAL'], dtype=object)

In [48]:
dictionary={'12TH':2, 'GRADUATE':3, 'SSC':1, 'POST-GRADUATE':4, 'UNDER GRADUATE':3,'OTHERS':1, 'PROFESSIONAL':5}
df_after_anova['EDUCATION']=df_after_anova['EDUCATION'].map(dictionary)

In [49]:
df_after_anova.EDUCATION.unique()

array([2, 3, 1, 4, 5], dtype=int64)

In [50]:
dictionary1={'P1':0, 'P2':1, 'P3':2, 'P4':3}
df_after_anova['Approved_Flag']=df_after_anova['Approved_Flag'].map(dictionary1)

In [51]:
df_after_anova.Approved_Flag.unique()

array([1, 0, 2, 3], dtype=int64)

In [52]:
df_after_anova.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 48 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Total_TL_opened_L6M           51336 non-null  float64
 1   Tot_TL_closed_L6M             51336 non-null  float64
 2   pct_tl_open_L6M               51336 non-null  float64
 3   pct_tl_closed_L6M             51336 non-null  float64
 4   Tot_TL_closed_L12M            51336 non-null  float64
 5   pct_tl_open_L12M              51336 non-null  float64
 6   pct_tl_closed_L12M            51336 non-null  float64
 7   Tot_Missed_Pmnt               51336 non-null  float64
 8   time_since_recent_payment     51336 non-null  float64
 9   num_times_delinquent          51336 non-null  float64
 10  max_recent_level_of_deliq     51336 non-null  float64
 11  max_deliq_12mts               51336 non-null  float64
 12  num_times_60p_dpd             51336 non-null  float64
 13  n

## We have converted the datatype to integer for categorical columns.

#### Splitting the data into independent and dependent variables

In [53]:
x=df_after_anova.drop('Approved_Flag',axis=1)
y=df_after_anova['Approved_Flag']

In [54]:
x.shape

(51336, 47)

In [55]:
y.shape

(51336,)

#### Splitting the data into train_test_split

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,random_state=42)

In [58]:
x_train.shape

(41068, 47)

In [59]:
x_test.shape

(10268, 47)

In [60]:
y_train.shape

(41068,)

In [61]:
y_test.shape

(10268,)

#### Analyzing the Dependent variable

In [62]:
y_train.value_counts(normalize=True)

Approved_Flag
1    0.628713
2    0.144054
0    0.113665
3    0.113568
Name: proportion, dtype: float64

#### From above we observe that our dataset is imbalanced. We will balance our dataset using SMOTE technique.

In [63]:
from imblearn.over_sampling import SMOTE

In [64]:
sm=SMOTE(random_state=42)
x_sm,y_sm=sm.fit_resample(x_train,y_train)

In [65]:
y_sm.value_counts()

Approved_Flag
0    25820
1    25820
3    25820
2    25820
Name: count, dtype: int64

#### Now we have observe that our dataset is balanced.

# Model Building

In [66]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [67]:
def final_model(classifier,x_sm,y_sm,x_test,y_test):
    model=classifier.fit(x_sm,y_sm)
    pred_train=model.predict(x_sm)
    pred_test=model.predict(x_test)
    
    # Confusion Matrix Train data
    print('Confusion Matrix on Training Data')
    cm_train=confusion_matrix(y_sm,pred_train)
    print(cm_train)
    
    # Confusion Matrix Test data
    print('Confusion Matrix on Test Data')
    cm_test=confusion_matrix(y_test,pred_test)
    print(cm_test)
    
    # Classification report Train data
    print('Classification report on Training Data')
    cr_train=classification_report(y_sm,pred_train)
    print(cr_train)
    
    # Classification report Test data
    print('Classification report on Test Data')
    cr_test=classification_report(y_test,pred_test)
    print(cr_test)
    
    return 'Final Model'
          
    
    
    
    

In [69]:
from sklearn.metrics import confusion_matrix,classification_report

# Decision Tree Classifier

In [70]:
classifier=DecisionTreeClassifier()
final_model(classifier,x_sm,y_sm,x_test,y_test)

Confusion Matrix on Training Data
[[25820     0     0     0]
 [    0 25820     0     0]
 [    0     0 25820     0]
 [    0     0     0 25820]]
Confusion Matrix on Test Data
[[1098    0   37    0]
 [   0 6349   30    0]
 [  34    0 1502    0]
 [   0    0    1 1217]]
Classification report on Training Data
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     25820
           1       1.00      1.00      1.00     25820
           2       1.00      1.00      1.00     25820
           3       1.00      1.00      1.00     25820

    accuracy                           1.00    103280
   macro avg       1.00      1.00      1.00    103280
weighted avg       1.00      1.00      1.00    103280

Classification report on Test Data
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1135
           1       1.00      1.00      1.00      6379
           2       0.96      0.98      0.97      1536
        

'Final Model'

# RandomForestClassifier

In [71]:
classifier=RandomForestClassifier()
final_model(classifier,x_sm,y_sm,x_test,y_test)

Confusion Matrix on Training Data
[[25820     0     0     0]
 [    0 25820     0     0]
 [    0     0 25820     0]
 [    0     0     0 25820]]
Confusion Matrix on Test Data
[[1102   20   13    0]
 [   0 6378    1    0]
 [  26   58 1452    0]
 [   0    0    0 1218]]
Classification report on Training Data
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     25820
           1       1.00      1.00      1.00     25820
           2       1.00      1.00      1.00     25820
           3       1.00      1.00      1.00     25820

    accuracy                           1.00    103280
   macro avg       1.00      1.00      1.00    103280
weighted avg       1.00      1.00      1.00    103280

Classification report on Test Data
              precision    recall  f1-score   support

           0       0.98      0.97      0.97      1135
           1       0.99      1.00      0.99      6379
           2       0.99      0.95      0.97      1536
        

'Final Model'

# AdaBoostClassifier

In [72]:
classifier=AdaBoostClassifier()
final_model(classifier,x_sm,y_sm,x_test,y_test)

Confusion Matrix on Training Data
[[25521     0   299     0]
 [    0 25820     0     0]
 [   28 24935   857     0]
 [    0     0 25820     0]]
Confusion Matrix on Test Data
[[1090    0   45    0]
 [   0 6379    0    0]
 [   1 1428  107    0]
 [   0    0 1218    0]]
Classification report on Training Data
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     25820
           1       0.51      1.00      0.67     25820
           2       0.03      0.03      0.03     25820
           3       0.00      0.00      0.00     25820

    accuracy                           0.51    103280
   macro avg       0.38      0.51      0.43    103280
weighted avg       0.38      0.51      0.43    103280

Classification report on Test Data
              precision    recall  f1-score   support

           0       1.00      0.96      0.98      1135
           1       0.82      1.00      0.90      6379
           2       0.08      0.07      0.07      1536
        

'Final Model'

# GradientBoostingClassifier

In [73]:
classifier=AdaBoostClassifier()
final_model(classifier,x_sm,y_sm,x_test,y_test)

Confusion Matrix on Training Data
[[25521     0   299     0]
 [    0 25820     0     0]
 [   28 24935   857     0]
 [    0     0 25820     0]]
Confusion Matrix on Test Data
[[1090    0   45    0]
 [   0 6379    0    0]
 [   1 1428  107    0]
 [   0    0 1218    0]]
Classification report on Training Data
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     25820
           1       0.51      1.00      0.67     25820
           2       0.03      0.03      0.03     25820
           3       0.00      0.00      0.00     25820

    accuracy                           0.51    103280
   macro avg       0.38      0.51      0.43    103280
weighted avg       0.38      0.51      0.43    103280

Classification report on Test Data
              precision    recall  f1-score   support

           0       1.00      0.96      0.98      1135
           1       0.82      1.00      0.90      6379
           2       0.08      0.07      0.07      1536
        

'Final Model'

# XGBClassifier

In [74]:
classifier=XGBClassifier()
final_model(classifier,x_sm,y_sm,x_test,y_test)

Confusion Matrix on Training Data
[[25820     0     0     0]
 [    0 25820     0     0]
 [    0     0 25820     0]
 [    0     0     0 25820]]
Confusion Matrix on Test Data
[[1097    0   38    0]
 [   0 6379    0    0]
 [  16    0 1520    0]
 [   0    0    0 1218]]
Classification report on Training Data
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     25820
           1       1.00      1.00      1.00     25820
           2       1.00      1.00      1.00     25820
           3       1.00      1.00      1.00     25820

    accuracy                           1.00    103280
   macro avg       1.00      1.00      1.00    103280
weighted avg       1.00      1.00      1.00    103280

Classification report on Test Data
              precision    recall  f1-score   support

           0       0.99      0.97      0.98      1135
           1       1.00      1.00      1.00      6379
           2       0.98      0.99      0.98      1536
        

'Final Model'

# We observe that Decision Tree Classifier, Random Forest Classifier and XGB Classifier gave pretty good results.